<?xml version="1.0" encoding="utf-8"?><Database Name="QLDTDD" Class="QLDTDDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLDTDD;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QLDTDDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="accID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Account_Employee" Member="Employees" ThisKey="accID" OtherKey="accID" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetail" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="detailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="unitprice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="orderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="teleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="orderID" OtherKey="orderID" Type="Order" IsForeignKey="true" />
      <Association Name="Telephone_OrderDetail" Member="Telephone" ThisKey="teleID" OtherKey="teleID" Type="Telephone" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="empID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="accID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_ImportCoupon" Member="ImportCoupons" ThisKey="empID" OtherKey="empID" Type="ImportCoupon" />
      <Association Name="Employee_Order" Member="Orders" ThisKey="empID" OtherKey="empID" Type="Order" />
      <Association Name="Account_Employee" Member="Account" ThisKey="accID" OtherKey="accID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImportCoupon" Member="ImportCoupons">
    <Type Name="ImportCoupon">
      <Column Name="impID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="impdetailDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="empID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="ImportCoupon_ImportCouponDetail" Member="ImportCouponDetails" ThisKey="impID" OtherKey="impID" Type="ImportCouponDetail" />
      <Association Name="Employee_ImportCoupon" Member="Employee" ThisKey="empID" OtherKey="empID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImportCouponDetail" Member="ImportCouponDetails">
    <Type Name="ImportCouponDetail">
      <Column Name="impdetaiID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="impID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ImportCouponDetail_Telephone" Member="Telephones" ThisKey="impdetaiID" OtherKey="impdetaiID" Type="Telephone" />
      <Association Name="ImportCoupon_ImportCouponDetail" Member="ImportCoupon" ThisKey="impID" OtherKey="impID" Type="ImportCoupon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="orderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="cusName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="orderDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="empName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="empID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="orderID" OtherKey="orderID" Type="OrderDetail" />
      <Association Name="Employee_Order" Member="Employee" ThisKey="empID" OtherKey="empID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Telephone" Member="Telephones">
    <Type Name="Telephone">
      <Column Name="teleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="impdetaiID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="provider" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Telephone_OrderDetail" Member="OrderDetails" ThisKey="teleID" OtherKey="teleID" Type="OrderDetail" />
      <Association Name="ImportCouponDetail_Telephone" Member="ImportCouponDetail" ThisKey="impdetaiID" OtherKey="impdetaiID" Type="ImportCouponDetail" IsForeignKey="true" />
    </Type>
  </Table>
</Database>